version: '3.6'
services:
  api:
    container_name: fashionblog
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fashion_blog?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1007
    ports:
    - 9090:9091
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1007
      POSTGRES_DB: fashion_blog
      POSTGRES_USER: postgres
    networks:
      - backend
    volumes:
    - my-db:/var/lib/postgresql

networks:
  backend:
volumes:
  my-db:
